export enum GQLThrowType {
  NOT_FOUND = 'NOT_FOUND',
  INVALID = 'INVALID',
  NOT_AUTHORIZED = 'NOT_AUTHORIZED',
  UNEXPECTED = 'UNEXPECTED',
  DUPLICATE = 'DUPLICATE',
  FORBIDDEN = 'FORBIDDEN',
  BAD_REQUEST = 'BAD_REQUEST',
  UNPROCESSABLE = 'UNPROCESSABLE',
  INTERNAL = 'INTERNAL',
  ALREADY_JOIN = 'ALREADY_JOINED',
}

export const CThrowType = {
  NOT_FOUND: 'AT-404',
  INVALID: 'AT-400',
  NOT_AUTHORIZED: 'AT-401',
  UNEXPECTED: 'AT-500',
  DUPLICATE: 'AT-409',
  FORBIDDEN: 'AT-403',
  BAD_REQUEST: 'AT-400',
  UNPROCESSABLE: 'AT-422',
  INTERNAL: 'AT-500',
  ALREADY_JOINED: 'AT-304',
};
